### ISSUE TITLE
Attribute Error when running test.py

### ISSUE THREAD

**Issue by oppressionslayer** [SebWouters/blanczos#1]
I compiled and created the lib file successfully, but i'm running into this error:
```
Constructed B
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-615-6b73bd96afc2> in <module>
     18 print("Constructed B")
     19 
---> 20 Nsol, result = blanczos.blanczos(B, len(B)/2, Nrow, Ncol)

AttributeError: module 'blanczos' has no attribute 'blanczos'
```

I ran cmake, then make from the root directory. I placed/duplicated the .so file into a 'build' directory. Let me know what i should do to resolve this error or if you have any ideas as to what i need to do to resolve this issue. Thanks!

**Comment by oppressionslayer** [comment]
I was able to get this running after restarting ipython3 and will close the issue. I do have a question though, can this be used for integer factorization and would you have any quick comments on how to implement this for that use.

**Comment by oppressionslayer** [comment]
I did have to change line 20 to this for the test to work:

```
Nsol, result = blanczos.blanczos(B, len(B)//2, Nrow, Ncol) 
```

I had to change len(B)/2 to len(B)//2  as the single slash raised a type error

**Comment by SebWouters** [comment]
This can be used for integer factorization. I don't think block Lanczos in binary arithmetic has many other uses.

An exemplary implementation of a multiple polynomial quadratic sieve (MPQS) can be found in https://github.com/SebWouters/JANS, where blanczos could replace gf2solver.

The golden standard in integer factorization is the general number sieve (GNS), though. I find section 6.2 of Crandall and Pomerance, Prime Numbers: A Computational Perspective, 2nd edition, https://doi.org/10.1007/0-387-28979-8 particularly instructive. Another reference which I haven't studied in depth yet, but which seems thorough, is Viet Pham Hoang, Integer Factorization with the General Number Field Sieve, http://thales.doa.fmph.uniba.sk/macaj/skola/atc/nfs/Integer%20factorization.pdf.
