### ISSUE TITLE
I Don't know how to run it

### ISSUE THREAD

**Issue by gonzalopg0** [SebWouters/blanczos#2]
OSSError: ../build/libblanczos.so: cannot open shared object file: No such file or directory.
This error appears when you try to run blanczos.py. 

Thank you for your help.

**Comment by gonzalopg0** [comment]
The problem is I have never used ctypes. When you run cdll.LoadLibrary(.../build/libblanczos.so), the libblanczos.so file where is? I have to download it? It has been deleted?

**Comment by SebWouters** [comment]
Did you build it all?

```
$ mkdir build
$ cd build/
$ cmake ..
$ make
$ make test
$ cd ../python/
$ python test.py
```

**Comment by gonzalopg0** [comment]
It works great. Thank you for your help.
